// priority: 99
onEvent('recipes', event => {

    event.remove({output: 'cyclic:generator_food'})
    event.remove({output: 'cyclic:computer_shape'})
    event.remove({output: 'cyclic:battery'})
    event.remove({output: 'cyclic:placer'})
    event.remove({output: 'cyclic:breaker'})
    event.remove({output: 'cyclic:forester'})
    event.remove({output: 'cyclic:miner'})
    event.remove({output: 'cyclic:structure'})
    event.remove({output: 'cyclic:harvester'})
    event.remove({output: 'cyclic:collector'})
    event.remove({output: 'cyclic:collector_fluid'})
    event.remove({output: 'cyclic:placer_fluid'})
    event.remove({output: 'cyclic:user'})
    event.remove({output: 'cyclic:conveyor'})
    event.remove({output: 'cyclic:fan'})
    event.remove({output: 'cyclic:fisher'})
    event.remove({output: 'cyclic:uncrafter'})
    event.remove({output: 'cyclic:wireless_transmitter'})
    event.remove({output: 'cyclic:wireless_receiver'})
    event.remove({output: 'cyclic:teleport'})
    event.remove({output: 'cyclic:filter_data'})
    event.remove({output: 'cyclic:shape_data'})
    event.remove({output: 'cyclic:settings_data'})
    event.remove({output: 'cyclic:location_data'})
    event.remove({output: 'cyclic:crusher'})
    event.remove({output: 'cyclic:fan_slab'})
    event.remove({output: 'cyclic:rotator'})
    event.remove({output: 'cyclic:wireless_item'})
    event.remove({output: 'cyclic:wireless_fluid'})
    event.remove({output: 'cyclic:wireless_energy'})
    event.remove({output: 'cyclic:energy_pipe'})
    event.remove({output: 'cyclic:item_pipe'})
    event.remove({output: 'cyclic:fluid_pipe'})
    event.remove({output: 'quark:pipe'})
})